# Generated by Django 5.1.1 on 2024-10-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECT1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='depart',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='details',
            name='year_of_joining',
            field=models.IntegerField(default=0),
        ),
    ]
