# Generated by Django 5.1.1 on 2024-10-19 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECT1', '0004_signup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='user',
        ),
    ]
